services:
  - type: web
    name: storefront-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./startup.sh"
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DATABASE_URL
        value: "postgresql://storefront_user:DwNnRY5evmcgWpZrhfsU5TwLgIJ6MhGj@dpg-d31a20gd13ps73e825ag-a.render-postgres.render.com:5432/storefront2"
